#!/usr/bin/env bash
#Displays I am invincible!!! when receiving a SIGTERM signal

function cleanup {
	echo "I am invincible!!!"
}

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap cleanup SIGTERM
done
